### ISSUE TITLE
CompileFlexFlyResources exception - URI is not hierarchical 

### ISSUE THREAD

**Issue by jflann** [memo33/metarules#2]
I'm attempting to run CompileFlexFlyResources and am receiving this exception:

```
$ sbt run
[info] welcome to sbt 1.6.2 (Eclipse Adoptium Java 11.0.15)
[info] loading project definition from D:\GitHub\Network-Addon-Mod\project
[info] loading settings for project network-addon-mod from build.sbt ...
[info] set current project to nam-controller (in build file:/D:/GitHub/Network-Addon-Mod/)
[info] compiling 1 Scala source to D:\GitHub\Network-Addon-Mod\target\scala-2.11\classes ...
[info] done compiling
[info] running metarules.module.CompileAllMetarules
[error] java.lang.IllegalArgumentException: URI is not hierarchical
[error]         at java.base/java.io.File.<init>(File.java:420)
[error]         at metarules.module.flexfly.CompileFlexFlyResources$$anonfun$3.apply(CompileFlexFlyResources.scala:70)
[error]         at metarules.module.flexfly.CompileFlexFlyResources$$anonfun$3.apply(CompileFlexFlyResources.scala:70)
[error]         at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
[error]         at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
[error]         at scala.collection.immutable.List.foreach(List.scala:383)
[error]         at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
[error]         at scala.collection.immutable.List.map(List.scala:286)
[error]         at metarules.module.flexfly.CompileFlexFlyResources$.main(CompileFlexFlyResources.scala:69)
[error]         at metarules.module.CompileAllMetarules$.main(CompileAllMetarules.scala:14)
[error]         at metarules.module.CompileAllMetarules.main(CompileAllMetarules.scala)
[error]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[error] stack trace is suppressed; run 'last Compile / run' for the full output
[error] (Compile / run) java.lang.IllegalArgumentException: URI is not hierarchical
[error] Total time: 5 s, completed Jul 2, 2022, 8:08:24 PM
```

I've simply placed the rhwResources.dat and flexFlyResources.dat into the main/resources folder as described and added flexfly.CompileFlexFlyResources.main(Array.empty) to CompileAllMetarules.scala.

Any help is much appreciated.

**Comment by memo33** [comment]
Thanks for the report. I have opened a PR downstream. I have not inspected the generated .dat file as I currently do not have the tools installed. Let me know if there is anything else.
